### ISSUE TITLE
Error when executing > ionic build android

### ISSUE THREAD

**Issue by cassiopaia** [limewallet/limewallet#14]
```c++
Running command: /Users/xx/Git/limewallet/platforms/android/cordova/build 
[Error: ANDROID_HOME is not set and "android" command not in your PATH. You must fulfill at least one of these conditions.]
ERROR building one of the platforms: Error: /Users/xx/Git/limewallet/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/xx/Git/limewallet/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)

```

i'm on OSX ! Or should i build IOS version instead then!?

**Comment by elmato** [comment]
On OSX you can build both.

In this case you where trying to build the android version.
Remeber that you need to point ANDROID_HOME to your android SDK root folder

**Comment by cassiopaia** [comment]
ok guess this will work :)
